### PR TITLE
51 sign up modal

### LINKED ISSUE #51: Sign up modal
SIgn up modal hiih
backendtei holboh

### PR DESCRIPTION
**Pull request by Amaraa0505**
signup modal hiilee arai duusaagu bga

### CODE REVIEW

**Review by BilguunBttgs — CHANGES_REQUESTED** [review]
duusgaarai

**Comment by Amaraa0505** [comment]
signup front bolon backend holboloo
[

](url)

**Comment by Amaraa0505** [comment]
signup front bolon backend holboloo

**Review by BilguunBttgs — APPROVED** [review]
goodjob

**Pull request merged**
